### ISSUE TITLE
Spar 1.0.x 

### ISSUE THREAD

**Issue by nightwolfzor** [sameeragarwal/blinkdb#5]
Are there plans to have Blink working with Spark 1.0.0/1.0.1?

**Comment by lazyman500** [comment]
Are there plans to have Blink working with Spark 1.10/1.1.1?

**Comment by mkanchwala** [comment]
Looking forward on it, would like to have Spark 1.5.x Support too.

**Comment by e-** [comment]
Same here. Spark 0.9.x is too old..

**Comment by sameeragarwal** [comment]
hey folks, we have a private repository that's built on spark 1.5.x that's currently in private beta. Send me a message if you'd like an early sneak peak! More details here: http://www.slideshare.net/SparkSummit/agarwal-zeng and https://spark-summit.org/2015/events/blinkdb-ola-supporting-continuous-answers-in-sparksql/

**Comment by e-** [comment]
@sameeragarwal  Awesome. Can I get access to the repository?

**Comment by chesterxgchen** [comment]
Sameer
     Like to experiments with the blinkdb. please let me know how to access
the repo.
     chester@alpinenow.com
     chesterxgchen@yahoo.com

Chester

**Comment by jake-aft** [comment]
Would be great to get access

**Comment by avishekjoy** [comment]
When are you releasing blink with spark-sql?

**Comment by HyukjinKwon** [comment]
@sameeragarwal Can I take a peek at the new one as well?

**Comment by artem-aliev** [comment]
@sameeragarwal Could I get access to the beta code?

**Comment by mmatuszak** [comment]
Can I get access to the new one as well?

**Comment by kotfic** [comment]
@sameeragarwal  I'm also interested in seeing the beta code if thats possible,  Thanks!

**Comment by chesterxgchen** [comment]
Has anyone get access ? Just curious, as I haven't heard anything

**Comment by sameeragarwal** [comment]
Thanks folks, I've added the last few people on this thread to the AMPLab read-only group as well. Please feel free to contact me at sameer@databricks.com in case you've any questions!

**Comment by kevin868** [comment]
Hi can anybody provide access to the latest code? I got left out because I didn't comment :)

**Comment by avishekjoy** [comment]
Me too left, can you add me

On Sat, Jan 30, 2016 at 7:29 AM, Kevin Wang notifications@github.com
wrote:

> Hi can anybody provide access to the latest code? I got left out because I
> didn't comment :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sameeragarwal/blinkdb/issues/5#issuecomment-177045756
> .

## 

Cheers
Avishek Bhattacharya

**Comment by yang-cao** [comment]
@sameeragarwal  
Can you add me in too. Would be great to use it in experimental study. Thanks.

**Comment by feiyanzhandui** [comment]
@sameeragarwal hi, can you add me in? I really want to experiment the new BlinkDB. Thanks!

**Comment by wxietoonca** [comment]
@sameeragarwal Hi, could you add me in? I have a HDFS 2.6 + SPARK 1.6; but can not use the older version (0.2.0) to connect. Thanks

**Comment by sameeragarwal** [comment]
We've a public repository based on Spark 1.4 (and 1.3) available at https://github.com/amplab/iolap. You can find the relevant patches to spark at https://github.com/amplab/iolap/tree/master/sql/hive/src/main/scala/org/apache/spark/sql/hive/online/. Thanks!

**Comment by devender-yadav** [comment]
I see no commits at https://github.com/amplab/iolap since May'16.  Is this project (or any fork of it) still alive?

**Comment by pyongjoo** [comment]
@devender-yadav We have been developing a related project (called VerdictDB): https://github.com/mozafari/verdictdb (you can see the authors are related). VerdictDB works under a more general setting than BlinkDB. Online aggregation (which is the idea behind "iolap") will also be added in a month or so to VerdictDB as we make a major update to become a commercial-grade system.
