### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by GuiSim** [sameeragarwal/blinkdb#8]
I thought BlinkDB was a very promising project. I do not see any activity on this fork or any other fork more recent than June 2014.

What's the current status? Is this project dead?

**Comment by elyast** [comment]
See discussion in #5 there is private version of BlinkDB that you could have access, if you ask one of the authors, I assume this one was just developer preview.

**Comment by GuiSim** [comment]
Oh! Ok.

It would be worth mentioning this in the README so people realize that the project is not dead, just going off the radar for now.

Thanks for the update.
